# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [2]:
s = 5

In [3]:
s

5

## Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

## Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [ ]:
type(s)

In [ ]:
type(v)

In [ ]:
type(m)

In [ ]:
s_array = np.array([5])

In [ ]:
type(s_array)

## Data shapes

In [ ]:
m.shape

In [ ]:
v.shape

In [ ]:
s.shape

In [ ]:
s_array.shape

## Creating a column vector

In [8]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [9]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [10]:
m+s

array([[10, 17, 11],
       [ 2,  5, 19]])

In [ ]:
m+s_array

In [11]:
v+s

array([10,  3,  9])

In [ ]:
v

In [12]:
v+s_array

NameError: name 's_array' is not defined

In [13]:
m+v

array([[10, 10, 10],
       [ 2, -2, 18]])