# Cómo trabajar con matrices

In [1]:
# import tensorflow as tf2

# Para que funcione con la version 2 instalada
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
session = tf.Session()

Instructions for updating:
non-resource variables are not supported in the long term


### 1. Cómo crear matrices

In [44]:
# Matriz Identidad, diagonal en 1
identity = tf.diag([1.,1.,1.,1.])
print(session.run(identity))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [72]:
A = tf.truncated_normal([3,4], seed=111)
print(session.run(A))

[[ 1.2910079  -0.9737109  -0.48691544  0.7412955 ]
 [ 0.5127296  -0.40166777 -0.1521489  -0.4775958 ]
 [-1.1741332   0.09014881  1.2294087   1.347107  ]]


#### Primera ejecucion
[[ 1.2910079  -0.9737109  -0.48691544  0.7412955 ]\
 [ 0.5127296  -0.40166777 -0.1521489  -0.4775958 ]\
 [-1.1741332   0.09014881  1.2294087   1.347107  ]]

#### Segunda ejecucion
[[-0.8626558  -1.1622976  -1.6311948   0.22248225]\
 [-0.28775376  1.1048324   1.3257728   1.0245075 ]\
 [ 1.2401348  -0.4767589   1.0515246   0.20953219]]

In [49]:
B = tf.fill([3,4], 1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [50]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.48213398 0.46685135 0.7535199 ]
 [0.01744568 0.26365232 0.05172765]
 [0.4787861  0.46492314 0.5998769 ]
 [0.61295605 0.41400385 0.8026756 ]]


In [51]:
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [73]:
# No da el resultado porque cada vez que sea hace Run vuelve a generar aleatoreamente los datos
print(session.run(A + B))

[[1987.1373 1986.8376 1986.3688 1988.2225]
 [1987.7123 1989.1049 1989.3258 1989.0245]
 [1989.2401 1987.5232 1989.0515 1988.2095]]


In [8]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print(session.run(tf.matmul(A,C))) # Multiplicar

[[ 1.4488206  -1.1942375   0.2742157 ]
 [ 0.33256462  0.44089812  0.9722261 ]
 [ 0.79254884 -0.5662762   0.04434573]]


In [10]:
print(session.run(tf.matmul(A, identity)))

[[-0.15774179  0.39617383 -0.6204685  -0.4049844 ]
 [ 0.27472886  0.16733699  0.7692019  -0.950687  ]
 [ 0.6868604   0.01075015  0.12331354  1.762285  ]]


## 3. Tranpuesta, determinante, inversa

In [11]:
# Transpuesta
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [12]:
print(session.run(tf.transpose(A)))

[[-0.6614315  -0.9467137  -0.76205075]
 [-0.11272998 -1.6409017   0.7444479 ]
 [ 0.3464253  -1.003457   -1.4076123 ]
 [ 0.27212295 -1.2833452   0.8448068 ]]


In [13]:
print(session.run(tf.matrix_determinant(D)))
# da 6.66 muy probable que no podamos calcular inversa

6.66133814775094e-16


In [14]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.], [-3., -6., -1], [0., 5, -3]]))
print(session.run(tf.matrix_determinant(E)))
# Se puede calcular la inversa

-40.0


In [15]:
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


## 4. Descomposición

In [16]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios

In [17]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [18]:
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
