# Operaciones por capas

In [1]:
#import tensorflow as tf

# Para que funcione con la version 2 instalada
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
session = tf.Session()

Instructions for updating:
non-resource variables are not supported in the long term


- $X \in \mathbb R_{3\times 4}$

In [5]:
import numpy as np
# creamos matriz a mano
my_array = np.array([[1.,3.,5.,7.],
                     [-2.,0.,7.,6.],
                     [-6.,-1.,0.,3.]])
my_array

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [7]:
x_vals = np.array([my_array, my_array+1])
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [8]:
x_data = tf.placeholder(tf.float32, shape=(3,4))

- $m_1 \in \mathbb R^4$
- $m_2, a_1\in \mathbb R$

In [44]:
# Todos los definimos como vectores
m1 = tf.constant([[1.], [0.], [-2.],[5.]]) # vector en columnas, mismo numero col que la matriz definida
m2 = tf.constant([[7.]])
a1 = tf.constant([[15.]])

$$[(X\cdot m_1)\cdot m_2]+a_1$$

In [45]:
prod1 = tf.matmul(x_data, m1) # (X * m1) -> me va a devolver 1 valor por fila
prod2 = tf.matmul(prod1, m2) # (X * m1) * m2
add1 = tf.add(prod2, a1) # [(X * m1) * m2] + a1

In [46]:
print('\n(X * m1)\n')
for x_val in x_vals:
    print(session.run(prod1, feed_dict={x_data: x_val}))

print('\n(X * m1) * m2\n')

for x_val in x_vals:
    print(session.run(prod2, feed_dict={x_data: x_val}))
    
print('\n[(X * m1) * m2] + a1\n')

for x_val in x_vals:
    print(session.run(add1, feed_dict={x_data: x_val}))


(X * m1)

[[26.]
 [14.]
 [ 9.]]
[[30.]
 [18.]
 [13.]]

(X * m1) * m2

[[182.]
 [ 98.]
 [ 63.]]
[[210.]
 [126.]
 [ 91.]]

[(X * m1) * m2] + a1

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
