# Trabajar con múltiples capas

In [1]:
#import tensorflow as tf

# Para que funcione con la version 2 instalada
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

import numpy as np
session = tf.Session()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# Vamos a representar una imagen, se definen por 4 dimensiones (numero imagen, alto, ancho, capa RGB)
x_shape = [1, 4, 4, 1] # como definimos numero imagen y capa en uno va a generar M4x4
x_val = np.random.uniform(size=x_shape)
x_val

array([[[[0.61865139],
         [0.83287203],
         [0.81022501],
         [0.28162705]],

        [[0.13420593],
         [0.96993321],
         [0.74251861],
         [0.08578612]],

        [[0.94483724],
         [0.52723008],
         [0.31192003],
         [0.79005195]],

        [[0.04689531],
         [0.61259709],
         [0.19779605],
         [0.89172917]]]])

In [3]:
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [9]:
# le defino 0.25 porque va a ser el promedio, (0.25 * 4) = 1, la cantidad de vreces que se va a mover
my_filter = tf.constant(0.25, shape = [2,2,1,1])

# las veces que se va a mover el kernel en la fila de una operacion a la siguiente,
# en este caso sera de a 2 columnas, el cuadradito seria de 2x2,
# me va a reducir la matriz a la mitad
my_strides = [1, 2, 2, 1] 

# Vamos a usan convolution en 2d, y filtramos acorde a ello
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides, padding='SAME', name = "Moving_Avg_Windows")

Formula para visualizacion la salida de la convolucion

$$\frac{W-F+2P}{S}+1$$
- W: dimensión de entrada
- F: dimensión del filtro
- P: padding
- S: stride

In [5]:
# Hace algo parecido a la funcion convolution con Ax+b y aplico sigmoide, una capa castomizada
def custom_layer(input_matrix):
    # squeeze -> puedo borrar las dimensiones extras, las que tenian uno
    input_matrix_squeezed = tf.squeeze(input_matrix)
    A = tf.constant([[1.,2.],[3.,4]])
    b = tf.constant(1., shape = [2,2])
    temp1 = tf.matmul(A, input_matrix_squeezed)
    temp2 = tf.add(temp1, b) ## Ax+b
    return tf.sigmoid(temp2)

In [6]:
with tf.name_scope('Custom_Layer') as scope:
    customlayer1 = custom_layer(mov_avg_layer)

In [10]:
# genera un archivo, para visualizarlo debo ejecutarlo por consola
#  tensorboard --logdir = 'multiple-layers'
# en nuestro caso genera error porque debemos instalar la version 1 de tensorboard
writer = tf.summary.FileWriter("multiple-layers", session.graph)
print(session.run(customlayer1, feed_dict={x_data: x_val}))
writer.close()

[[0.9373031 0.9292869]
 [0.9936208 0.9903549]]


In [8]:
print(session.run(mov_avg_layer, feed_dict={x_data: x_val}))

[[[[0.63891566]
   [0.4800392 ]]

  [[0.53288996]
   [0.5478743 ]]]]
